import './globals.css'
import { Inter } from 'next/font/google'
import { Providers } from './GlobalRedux/provider'
import Head from 'next/head'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'ERT Website',
  description: 'Generated by create next app',

}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
   
      <body className={inter.className}>
      <Providers>
        {children}
      </Providers>
        </body>
    </html>
  )
}
